### ISSUE TITLE
Remove pytorch-3dunet dependency from plantseg

### ISSUE THREAD

**Issue by wolny** [hci-unihd/plant-seg#130]

**Comment by unidesigner** [comment]
Hi!

I just came across this issue via the pytorch-3dunet package because Issues are not enabled on this repo. Can you tell me why you remove this dependency? Is pytorch-3dunet not going to be developed any further?

I was trying to run the `3DUnet_confocal_boundary` config with the example data and unfortunately, I ran against an exception on my 1 GPU 8GB machine that I cannot resolve:
```
  File "/opt/miniconda3/envs/pytorch3dunet/lib/python3.9/site-packages/torch/nn/functional.py", line 2530, in group_norm
    return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument weight in method wrapper_CUDA__native_group_norm)
```
I already tried setting `device: cuda:0` in the config, but it did not help. Do you have any advice on how to resolve this?

Thank you, and sorry for abusing this issue for this offtopic question :)

**Comment by unidesigner** [comment]
I am using a single GPU machine. This [SO question](https://stackoverflow.com/questions/70102323/runtimeerror-expected-all-tensors-to-be-on-the-same-device-but-found-at-least) suggested adding a `model.to(device)`. So added
```
device = torch.device("cuda" if torch.cuda.is_available() else 'cpu')
model = model.to(device)
```
in `def create_trainer` and this seems to have helped. The network is training now.
