### ISSUE TITLE
Napari UI: Widgets too wide yet don't have enough space for numbers to show

### ISSUE THREAD

**Issue by qin-yu** [hci-unihd/plant-seg#213]
![image](https://github.com/hci-unihd/plant-seg/assets/17722010/d2d14303-400d-43d3-bef2-764a368b2341)

**Comment by qin-yu** [comment]
Hi @tlambert03, I need your help again! 

I am aiming to adjust the font size via label styling for the `FloatRangeSlider` (derived from `superqt`'s `QLabeledRangeSlider`?). I've reviewed the existing code, but found the implementation somewhat complex. Before I delve deeper, I wanted to reach out for your guidance. Could you provide any pointers on how I might approach this?

**Comment by tlambert03** [comment]
fwiw, this really is a napari issue, and not something that you should be having to worry about.  The issue is that napari doesn't do a great job of detecting display scaling (because it's a legitimately hard thing to do).  is it safe to assume you're on windows?  that's really where this will show up the most. 

One warning: if you try to fix this by hard-setting a font size based on what you see on your monitor, it's very likely that you'll be ruining it for another monitor (like a linux/macos system for which display scaling is better detected by Qt), so I'd encourage you to try to test whatever fix you come up with on different OSes

that said... to just adjust the font size, did you already try `some_slider.setStyleSheet("font-size: 8pt;")` ?  that should work

**Comment by qin-yu** [comment]
I'm running this through VNC on a Linux server, with displays eventually outputting to Windows/macOS machines at work/home. It seems that changing the font size doesn't have any effect, possibly due to the lack of a defined screen resolution, and I've configured the VNC to adjust interface window size responsively.

Given these circumstances, I think it's best to leave this issue as is. I'll mark it as "won't fix" for now. Your assistance has been invaluable—otherwise I would spend days trying to tweak Qt styling : ) 

Thank you so much!

**Comment by tlambert03** [comment]
> It seems that changing the font size doesn't have any effect

if i make a simple example of creating a QLabeledSlider and calling `setStyleSheet`, it does work for me.  so if it's not working for you, the answer is more likely related to napari's styles overriding your styles somehow, and that gets much more complicated (and is probably something you should take up with napari)

**Comment by qin-yu** [comment]
Ohhh, thanks @tlambert03! The stylesheet you provided is perfect. Initially, I was using `.setStyleSheet("QLabel { font-size: 8pt; }")`, guided by the examples at [Qt Style Sheet Examples](https://doc.qt.io/qt-6/stylesheet-examples.html), which unfortunately didn't work in my setup. Your solution resolved the issue completely—now it's fixed! I really appreciate your help!

**Comment by qin-yu** [comment]
![image](https://github.com/hci-unihd/plant-seg/assets/17722010/bcb23643-f773-4e41-b3bf-b8c91bba4a3b)
