### ISSUE TITLE
No cuda selection at predictions on Napari GUI

### ISSUE THREAD

**Issue by Giannisbiol** [hci-unihd/plant-seg#242]
Hello, as the title says, please check snapshot below too.

Cheers

![image](https://github.com/hci-unihd/plant-seg/assets/169128507/42a75197-87b1-4d0a-9452-bd03e9cf1a86)

**Comment by qin-yu** [comment]
Could you share your PlantSeg version and system information? 

Also, please check if the following code gives `True`, because I don't think your cards are visible to PlantSeg: 

```python
import torch
torch.cuda.is_available()
```

Even without `CUDA_VISIBLE_DEVICES`, PlantSeg should discover all graphic cards if they are available: 

![image](https://github.com/hci-unihd/plant-seg/assets/17722010/9d298eb9-6d3f-4563-811f-6c4605b318aa)

**Comment by Giannisbiol** [comment]
Version: 1.7.1 / System: Windows 11 / nvidia gf card: RTX 3500 Ada, CUDA vers. 12.4, driver version: 552.22 (think the latest, havent checked).

I get False actually from the code.

**Comment by qin-yu** [comment]
> I get False actually from the code.

That means PyTorch doesn't see any graphics card available, and PlantSeg only show devices available to PyTorch. The problem is very likely to be CUDA installation. It is very hard to tell what exactly breaks the environment, and Google/ChatGPT would give you a list of things to check. But I would start to look into this problem by checking what packages your `mamba` actually installed by running `conda list` (focus on the ones that has `cuda` or `cu` in their names).

**Comment by Giannisbiol** [comment]
Hi again. I did a mistake during installation. Instead of pytorch-cuda=12.1 i put pytorch-cuda=12.4, because of the cuda version of my card. Apologies for bothering you.

Cheers!

**Comment by qin-yu** [comment]
Congrats! No worries
