### ISSUE TITLE
crop_volume error in GUI Plantseg 1.3

### ISSUE THREAD

**Issue by moritzgraeff** [hci-unihd/plant-seg#73]
Hello
I just updated the Plantseg environment on my System, using Linux, and wanted to test some of the new models with the GUI.
When I set up the image and press run, Plantseg returns an error message with the last line reading:

RuntimeError: key : 'crop_volume' is missing, plant-seg requires 'crop_volume' to run

I tried to enter several values in the new crop volume field, from leaving it empty to [0:, 0:, 0:] and trying different other numers to specify the range, like [0:10, 0:10, 0:10]. The returned error is always the same. I could not find any updated entries explaining this new parameter. Could you add that to the documentation or look into the error?
Greetings Moritz

**Comment by lorenzocerrone** [comment]
Hello Moritz, 

Thanks for letting us know, indeed it's a bug. The issue is that when you launched PlantSeg 1.3.x for the first time, PlantSeg looked for the latest session saved and found an old and incompatible version. 
The solution is very simple, you just need to remove the `last_config_gui_last.yaml` file:
`rm -rf ~/.plantseg_models/configs/config_gui_last.yaml`

Please let me know if this fixed your issue or if the problem persists. 

By now I will add this to the troubleshooting guide. But still, the `reset config` button should handle this instance, I am not sure why this is not the case but I will fix it in the next release. 

Best,

Lorenzo

**Comment by moritzgraeff** [comment]
Great, I will try it out and let you know.

Thanks for your help

Moritz

**Comment by moritzgraeff** [comment]
Hello Lorenzo
Sorry for the late reply, I only came now to run the tests and change the
settings. Removing the od config file worked and everything is running well
now
Thanks again
Greetings Moritz

Am Sa., 20. März 2021 um 20:19 Uhr schrieb lorentz_liketheforce <
***@***.***>:
