### ISSUE TITLE
[Help] PNAS model questions

### ISSUE THREAD

**Issue by supersubscript** [hci-unihd/plant-seg#74]
Hi, thanks again for providing this tool - I'm having much use of it in my projects.

I have some questions about the PNAS models, which are trained using the Willis and Refahi et al. (2016) dataset. I know that this dataset had its resolution manually corrected due to artificial stretching stemming from plant growth during imaging, and therefore the resolution varies quite a bit between both plant by plant, but also between time-points for the same plant. How have you accounted for this, given that the resolution you list for the model is (.25, .25 .25) um? I think some plants also differ in terms of XY resolution, and I think plant 1 in the dataset has some wounded cells in its first time-points...

Secondly, the PNAS dataset suffers quite a bit from signal penetration bias, where the epidermal signal is strong, but the internal signal is much more sketchy. The authors conducted manual corrections to improve the segmentation, but AFAIK only for cells in the epidermis, within something like 45 um from the apex. 

I would ideally like to use this model to segment confocal SAM data in lower resolution ~(.5, .25, .25) um, but would like to achieve decent segmentations also for L2 and L3. Due to my questions above, I would like to avoid any biases due to the data the model is trained on. For achieving better segmentation of the subepidermal cells, would it be better to use the ovule models given the layer-bias in the PNAS dataset?

Thanks!

/ Henrik

**Comment by lorenzocerrone** [comment]
Hi Henrik, 

Thanks a lot for using plantseg! I am happy that it is useful for your project. 

Sorry for the late answer but I have been not available for the last two weeks. 


You are right about the PNAS dataset penetration bias. Indeed the ground truth segmentation quality degrades quite sharply with depth.  Anyway, I have trained the PNAS model on the publicly available version as it is. 
Empirically, I find out that the PNAS model generalizes well for some type of plant tissues (qualitatively, tissues with small cells and noisy images) I am working on at the moment. Since the model was useful in those projects of mine, I decided to publish it. But I have not invested a great amount of work in tuning the training or processing the ground truth segmentation, so I am sure that with some more effort the model could improve.

@wolny do you have any script to clean the PNAS data or any trained models? I remember that you worked quite a bit with this dataset. Maybe we could use your processing :) 

That said, it is really hard to know in advance if the PNAS dataset biases will influence your predictions. You will probably need to test both models and evaluate the L2/L3 performances. But, given the resolution in your data, I think that the PNAS should still perform better than the ovules.

About the resolution, this is all my fault. I have not noticed that the resolution varied between time points. I will change the model resolution to the average voxel resolution inside plantseg and I will comment on that in the README.md.


Best,

Lorenzo

**Comment by wolny** [comment]
Hi Henrik,

just for completeness on my part: for training/evaluation of the models based on the for the dataset published in PNAS (https://www.pnas.org/content/113/51/E8238) we filter all of the regions in the ground truth which are bigger than `6 x median_cell_size`.

Best,
Adrian

**Comment by supersubscript** [comment]
That's very helpful, thanks both for taking the time to answer this. I will test the SAM model out. :) 

I'm sure you have a million things on your hands with this, but in case you're interested in hearing community requests, I think models trained on low-resolution data (e.g. z-resolution of > 0.5 um) would be very useful for a lot of people. 

Closing this issue due to the very helpful replies. Thanks!
