### ISSUE TITLE
Issue when running the GUI in version 1.3.5

### ISSUE THREAD

**Issue by pformosa** [hci-unihd/plant-seg#78]
When running the GUI in the new version 1.3.5, the following error appears: 

FIle "...plantsegv1.3.5/lib/python3.7/site-packages/plantseg/pipeline/config_validation.py", line 182, in recursive_config_check raise RuntimeError(f'key: '{key}' is missing, plant-seg requires '{key}' to run:). RuntimeError: key: 'crop_volume' is missing, plant-seg requires 'crop_volume' to run. 

The command line runs well though. We tested a previous GUI version (v.1.1.8) and it was working well as well. 

Thanks!

Best 

Pau

**Comment by lorenzocerrone** [comment]
Hi Pau, 

Thanks for reaching out to us and sorry for the inconvenience. The bug is going to be removed in one of the next releases, but luckily there is an easy fix. 

Here https://github.com/hci-unihd/plant-seg/issues/73#issuecomment-803449646 you can see the full story but in short:

> The solution is very simple, you just need to remove the last_config_gui_last.yaml file:
rm -rf ~/.plantseg_models/configs/config_gui_last.yaml

Best, 

Lorenzo
