### ISSUE TITLE
Docker container not working

### ISSUE THREAD

**Issue by palfalvi** [hci-unihd/plant-seg#92]
Hi,

I wanted to install plant-seg on Ubuntu 18 with a GForce RTX 2070. There were a lot of dependency issues due to other software relying on specific version of CUDA, hence I decided to use Docker. Nvidia docker is working, and plantseg GUI is also starting. However, when I try to run any predictions, there are two isses:

1, Torch cannot recognize the gpu, even when I include --gpu all in the docker command
`key: device has got value: cuda, but torch can not detect a valid cuda device. defaulting default value: cpu`

2, plantseg failes after downloading the model files and starting network prediction
I can see, that the memory usage goes up until ~25 Gb (64Gb RAM in the PC) for a few second and than this error message:
` File "/root/miniconda3/envs/plant-seg/lib/python3.8/site-packeges/torch/utils/data/dataloader.py", line 999, in _try_get_data raise RuntimeError('DataLoader worker(pid(s) {}) exied unexpectedly' .format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 39, 73) exited unexpectedly `

I am using one of the example tif for the setup: `Col0_03_T1.tif` with default setting. I tried several model files and other images, same results.

I would appreciate some help to make the software work with docker. Thanks in advance.

Cheers,
Gergo

**Comment by wolny** [comment]
hey @palfalvi,

thanks for opening the PR and a detailed description of your problem and setup.

The issue you described in 1) is most likely caused by your `nvidia-docker` not being configured properly, since the CUDA device cannot be recognized by pytorch. But apart from that: our docker image is only meant to be used on Windows/MacOS and on Linux one should just install PlantSeg directly from conda (see installation instructions: https://github.com/hci-unihd/plant-seg#install-plantseg-using-conda).

Cheers,
Adrian
